spring.application.name=TestJurnal

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5433/online_jornal_data_base
spring.datasource.username=postgres
spring.datasource.password=postgres

# JWT Configuration
jwt.secret.key=vashochendlinniyisekretniykluch32simvolaminimum
jwt.token.time=86400000